# Generated by Django 2.1.15 on 2019-12-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='place',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
